version: "3.8"

services:
  app-m1:
    build:
      context: .
      dockerfile: ./docker/dev/m1/Dockerfile
    container_name: app-m1
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - internal
    restart: always
  app-m2:
    build:
      context: .
      dockerfile: ./docker/dev/m2/Dockerfile
    container_name: app-m2
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - internal
    restart: always
  rabbitmq :
    image: rabbitmq:3.9-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - internal
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

networks:
  internal:
    name: ${APP_NAME}-net
