name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build m1 Docker image
      run: docker build . --file docker/dev/m1/Dockerfile --tag app-m1:$(date +%s) --tag app-m1:latest
    
    - uses: actions/checkout@v3
    - name: Build m2 Docker image
      run: docker build . --file docker/dev/m2/Dockerfile --tag app-m2:$(date +%s) --tag app-m2:latest

    - uses: redhat-actions/push-to-registry@v2.7
    - name: Push to registry m1 Docker image
      with:
        image : app-m1:$(date +%s) app-m1:latest
        registry: registry.rangeray.ru:5000
        username : ${{secrets.REGISTRY_USER}}
        password : ${{secrets.REGISTRY_PASSWORD}}
    
    - uses: redhat-actions/push-to-registry@v2.7 
    - name: Push to registry m2 Docker image
      with:
        image : app-m2:$(date +%s) app-m2:latest
        registry: registry.rangeray.ru:5000
        username : ${{secrets.REGISTRY_USER}}
        password : ${{secrets.REGISTRY_PASSWORD}}
    
        
        
    
