name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build m1 Docker image
        run: docker build . --file docker/dev/m1/Dockerfile --tag {{vars.REGISTRY_URL}}/app-m1:latest

      - name: Build m2 Docker image
        run: docker build . --file docker/dev/m2/Dockerfile --tag {{vars.REGISTRY_URL}}/app-m2:latest

  push-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker registry
        run: docker login {{vars.REGISTRY_URL}} -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASSWORD}}

      - name: Push to registry m1 Docker image
        run: docker push {{vars.REGISTRY_URL}}/app-m1:latest

      - name: Push to registry m2 Docker image
        run: docker push {{vars.REGISTRY_URL}}/app-m2:latest

