name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build m1 Docker image
        run: docker build . --file docker/dev/m1/Dockerfile --tag registry.rangeray.ru:5000/app-m1:latest

      - name: Build m2 Docker image
        run: docker build . --file docker/dev/m2/Dockerfile --tag registry.rangeray.ru:5000/app-m2:latest

      - name: Login to Docker registry
        run: docker login registry.rangeray.ru:5000 -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASSWORD}}

      - name: Push to registry m1 Docker image
        run: docker push registry.rangeray.ru:5000/app-m1:latest

      - name: Push to registry m2 Docker image
        run: docker push registry.rangeray.ru:5000/app-m2:latest
